### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by NameNotTakenYAY** [guzlewski/EasyLicense-Legacy#7]
what does "Add C# files to your project and input url and productname (program exemple in C#/EasyLicenseExample) Thats all, if you did everything properly it should work." mean?

**Comment by guzlewski** [comment]
When web part is working you have to add auth class to your program. You have to copy these files and add them to visualstudio project 
<img src="https://sharex.geniush.ovh/6e4bd/5d43cdc9a3aa4.png/raw">
Also you have to install [Leax.xNet](https://github.com/csharp-leaf/Leaf.xNet) to project via Nuget.
