### ISSUE TITLE
URL is set too?

### ISSUE THREAD

**Issue by NameNotTakenYAY** [guzlewski/EasyLicense-Legacy#8]
what do i set url to? my website name? i cant firgure it out

**Comment by guzlewski** [comment]
<img src="https://sharex.geniush.ovh/6e4bd/5d43cb8a1dad6.png/raw">
Url in c# part is url to www/login/index.php. So if you upload content of www folder to web server admin dashbord is avaible at http/https://example.com/admin/index.php and url for login (C# part) is http/https://example.com/login/index.php

**Comment by NameNotTakenYAY** [comment]
thx. 

> ![](https://camo.githubusercontent.com/9ee6e8dc9b3fba8462ea39fd2cf42cb260df423c/68747470733a2f2f7368617265782e67656e697573682e6f76682f36653462642f356434336362386131646164362e706e672f726177)
> 
> Url in c# part is url to www/login/index.php. So if you upload content of www folder to web server admin dashbord is avaible at http/https://example.com/admin/index.php and url for login (C# part) is http/https://example.com/login/index.php

Thank u. Any chnace you can add a login system to the admin panel :)

**Comment by guzlewski** [comment]
I'm working on new version with login system, but I will release it when it will be fully working, ETA 6 months.
